"""Component 5: Orchestrator + handoff.

One pass, single attempt, no retry:

    claim an Implementing issue
      -> make isolated git worktree (darkfactory/<id>)
      -> build prompt
      -> run coding agent (cwd == worktree)
      -> git add -A && git commit
      -> gh pr create (base main, head darkfactory/<id>)
         (falls back to a clearly-marked SIMULATED PR url if gh is unauthed
          or push is denied)
      -> AttachPr(pr_url) back onto the issue

Never pushes to ``main``; never deletes the Helix working tree or existing
branches (the WorkspaceManager only touches its own ``darkfactory/*``).
"""

from __future__ import annotations

import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from .agent import CodingAgent, make_agent
from .config import SymphonyConfig
from .prompt import build_prompt
from .tracker import Issue, Tracker, make_tracker
from .workspace import Workspace, WorkspaceManager


@dataclass
class PassResult:
    """Everything observable about a single orchestrator pass (the evidence)."""

    picked_up: bool = False
    issue_id: str = ""
    branch: str = ""
    worktree_path: str = ""
    commit_sha: str = ""
    diffstat: str = ""
    pr_url: str = ""
    pr_simulated: bool = False
    attach_result: dict = field(default_factory=dict)
    agent_summary: str = ""
    notes: list[str] = field(default_factory=list)

    def log(self, msg: str) -> None:
        self.notes.append(msg)
        print(f"[symphony] {msg}")


class Orchestrator:
    """Wires the five components together for one pass."""

    def __init__(
        self,
        config: SymphonyConfig,
        tracker: Optional[Tracker] = None,
        workspace_mgr: Optional[WorkspaceManager] = None,
        agent: Optional[CodingAgent] = None,
    ) -> None:
        self.config = config
        self.tracker = tracker or make_tracker(config)
        self.workspaces = workspace_mgr or WorkspaceManager(config)
        self.agent = agent or make_agent(config)

    # ---- git / gh helpers -------------------------------------------------

    @staticmethod
    def _git(cwd: Path, *args: str) -> subprocess.CompletedProcess:
        return subprocess.run(["git", *args], cwd=str(cwd), capture_output=True, text=True)

    def _commit(self, ws: Workspace, issue: Issue) -> tuple[str, str]:
        """Stage everything and commit on the worktree branch. Returns (sha, diffstat)."""
        self._git(ws.path, "add", "-A")
        diffstat = self._git(ws.path, "diff", "--cached", "--stat").stdout.strip()
        message = (
            f"darkfactory({issue.id}): {issue.title}\n\n"
            f"{issue.plan}\n\n"
            f"Generated by Symphony orchestrator from ImprovementIssue {issue.id}.\n\n"
            "Co-Authored-By: Claude Opus 4.7 <noreply@anthropic.com>"
        )
        r = self._git(ws.path, "commit", "-m", message)
        if r.returncode != 0:
            # Nothing to commit (agent made no change) is a real failure here.
            return "", diffstat
        sha = self._git(ws.path, "rev-parse", "HEAD").stdout.strip()
        return sha, diffstat

    def _open_pr(self, ws: Workspace, issue: Issue, result: PassResult) -> tuple[str, bool]:
        """Open a PR via gh. Returns (url, simulated?).

        Push + PR are attempted; if gh is unauthenticated, the remote rejects the
        push, or PR creation fails, we DO NOT touch main — we print the diff and
        return a clearly-marked simulated PR url instead.
        """
        # 1. Try to push the branch (never main).
        assert ws.branch != self.config.base_branch, "refusing to push base branch"
        push = self._git(ws.path, "push", "-u", "origin", ws.branch)
        if push.returncode != 0:
            result.log(f"git push failed (not authed / no perms): {push.stderr.strip().splitlines()[-1:] }")
            return self._simulate_pr(ws, issue, result, reason="push failed")

        # 2. Try gh pr create.
        body = (
            f"Automated PR from the Dark Factory pipeline for ImprovementIssue "
            f"`{issue.id}`.\n\n"
            f"**Hypothesis:** {issue.hypothesis}\n\n"
            f"**Plan:** {issue.plan}\n\n"
            f"**Acceptance criteria:** {issue.acceptance_criteria}\n\n"
            "🤖 Generated with [Claude Code](https://claude.com/claude-code)"
        )
        pr = subprocess.run(
            [
                "gh", "pr", "create",
                "--base", self.config.base_branch,
                "--head", ws.branch,
                "--title", f"darkfactory({issue.id}): {issue.title}",
                "--body", body,
            ],
            cwd=str(ws.path),
            capture_output=True,
            text=True,
        )
        if pr.returncode != 0:
            result.log(f"gh pr create failed: {pr.stderr.strip()}")
            return self._simulate_pr(ws, issue, result, reason="gh pr create failed")

        url = pr.stdout.strip().splitlines()[-1] if pr.stdout.strip() else ""
        result.log(f"opened real PR: {url}")
        return url, False

    def _simulate_pr(self, ws: Workspace, issue: Issue, result: PassResult, reason: str) -> tuple[str, bool]:
        diff = self._git(ws.path, "diff", f"{self.config.base_branch}...{ws.branch}").stdout
        result.log(f"SIMULATED PR ({reason}). Diff on branch {ws.branch}:")
        print("-" * 70)
        print(diff if diff.strip() else "(no diff)")
        print("-" * 70)
        sim_url = (
            f"SIMULATED://pr/{issue.id}?branch={ws.branch}&base={self.config.base_branch}"
            f"&reason={reason.replace(' ', '_')}"
        )
        return sim_url, True

    # ---- main pass --------------------------------------------------------

    def run_once(self, *, cleanup: bool = False) -> PassResult:
        result = PassResult()

        # 1. Claim work.
        issue = self.tracker.claim_issue()
        if issue is None:
            result.log("no Implementing issue to pick up; nothing to do.")
            return result
        result.picked_up = True
        result.issue_id = issue.id
        result.log(f"claimed issue {issue.id}: {issue.title}")

        # 2. Isolated worktree (enforces the 3 invariants).
        ws = self.workspaces.create(issue.branch_name or issue.id)
        result.branch = ws.branch
        result.worktree_path = str(ws.path)
        result.log(f"worktree at {ws.path} on branch {ws.branch}")

        # 3. Prompt.
        prompt = build_prompt(issue)

        # 4. Run agent — assert cwd invariant first (invariant 1).
        self.workspaces.assert_cwd(ws, ws.path)
        agent_res = self.agent.run(prompt, ws.path)
        result.agent_summary = agent_res.summary
        result.log(f"agent finished (ok={agent_res.ok}): {agent_res.summary[:200]}")
        if not agent_res.ok:
            result.log("agent failed; aborting pass (single attempt, no retry).")
            if cleanup:
                self.workspaces.remove(ws)
            return result

        # 5. Commit.
        sha, diffstat = self._commit(ws, issue)
        result.commit_sha = sha
        result.diffstat = diffstat
        if not sha:
            result.log("agent produced no committable change; aborting.")
            if cleanup:
                self.workspaces.remove(ws)
            return result
        result.log(f"committed {sha} on {ws.branch}\n{diffstat}")

        # 6. PR (real or simulated).
        pr_url, simulated = self._open_pr(ws, issue, result)
        result.pr_url = pr_url
        result.pr_simulated = simulated

        # 7. Handoff: write PR url back onto the issue (AttachPr).
        result.attach_result = self.tracker.attach_pr(issue, pr_url)
        result.log(f"AttachPr result: {result.attach_result}")

        if cleanup:
            self.workspaces.remove(ws)
        return result
